title: Andrey Zonov
email: andryzonov@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Andrey Zonov's personal page, Senior iOS Developer, technical architect, lecturer at VSU.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://azonov.com"
twitter_username: avzonov
github_username:  azonov

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  groups:
    output: true